### ISSUE TITLE
YELL Live: Incorrect state labels along borders

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/park-tiles#170]
A visitor at Yellowstone pointed out that our YELL Live maps in the kiosks are showing incorrect labels for states. The labels in question are the ones that appear on either end of the grey dotted border between states. These labels were custom designed and placed so we should be able to update the data source to fix the issue. @mtaylorlong will take the first crack at it.

![screen shot 2015-09-08 at 5 28 36 pm](https://cloud.githubusercontent.com/assets/4741443/9749957/1b9bedd8-564f-11e5-9d87-934402fc4f74.png)

Montana should be above Wyoming, and Idaho should be to the West.

cc @nateirwin, @jakecoolidge

**Comment by mtaylorlong** [comment]
I've looked into the Mapbox project to identify the moving parts here. Oddly enough, the labels are correctly placed when you look at the project through Mapbox Studio. All the styles seem to be correctly written as well. All this is to say that the problem likely did not exist until recently, and probably has something to do with a Mapbox update interpreting our existing styles differently. The problem seems to lie in the `text-dy` property.

Here's what it looks like in Studio:
![screen shot 2015-09-09 at 12 27 48 pm](https://cloud.githubusercontent.com/assets/4741443/9770604/3ca25ffe-56ee-11e5-900f-d49922378b5a.png)

The line of CartoCSS determining the text's position along the state boundary line is:
```css
#state_line_labels[zoom>=9][zoom<=11]{
  text-name: [STATE];
  text-size:14;
  text-face-name: "Frutiger LT Std 55 Roman";
  text-placement: line;
  text-transform: uppercase;
  text-dy: -5;
  text-character-spacing: 1;
  text-fill: lighten(#909090,1);
  text-avoid-edges: true;
  [zoom=9]{text-size:11;}
  [zoom=10]{text-size:12;}
  }
```
`text-dy: -5;` is what's making the labels show inside the border of their respective state polygon. **If I switch `-5` to `5`, I can recreate the issue we're seeing on the kiosk map.** So it looks like something is being lost in the interpretation from CartoCSS to Mapnik. This may have something to do with Mapnik updates that @nateirwin has mentioned recently. I bet if we look at updates to text properties, we'll find our culprit.
